<div class="contact_wraper">
	<div class="container">
		<div class="row">	
				<div class="col-sm-8 col-md-8">
					<p><strong>Online Indian Grocery Store in Sweden</strong></p>
					<p>Nila Groceries AB is a grocery online store operating in Stockholm with deliveries to all main cities across Sweden. We carry full selection of Indian Groceries and Fresh Vegetables direct from farmers and offer grocery home delivery as well as a grocery shop online for you to purchase from our online grocery store has&nbsp;Rices, Spices, Pulses, Millets, Cold Pressed oils, Ghee, Jaggery Powder, Palm Sugar and etc. Each product is one link in a chain of connectedness between Mother Nature, our farmers and you.</p>
					<div class="share-links">
						<a href="https://www.facebook.com/NilaGroceries" class="share-facebook"></a>
						<a href="#"class="share-twitter"></a>
						<a href="#"class="share-linkedin"></a>
						<a href="#"class="share-youtube"></a>
						<a href="#"class="share-instagram"></a>
						<a href="#"class="share-skype"></a>
					</div>
				</div>
				<div class="col-sm-4 col-md-4 text-center">
					<div class="rect">
						<div class="animate scale icon-outer animated"></div>
						<h6><strong></strong>OPENING TIME</h6>
						<p>We are operating as Online Grocery Store 24/7</p>
					</div>
				</div>
		</div>
	</div>
</div>